"""CLI for a single A or B Xray reverse-proxy agent."""

import argparse
import asyncio
import logging
import sys
from pathlib import Path

from .app import Agent
from .config import init_config


async def run(role: str, path: Path):
    agent = Agent(role, path)
    try:
        await agent.start()
        config = agent.config
        print(f"mytrn {role.upper()} started; Web UI http://{config['web_bind']}:{config['web_port']}", flush=True)
        print("Use admin_token generated by 'python -m mytrn init' to manage it.", flush=True)
        await agent.shutdown.wait()
    finally:
        await agent.stop()


def main() -> int:
    cli = argparse.ArgumentParser(description="A uses B Internet; B dials A over WARP SOCKS5 UDP/Xray mKCP")
    subs = cli.add_subparsers(dest="command", required=True)
    for role in ("a", "b"):
        task = subs.add_parser(role, help=f"start {role.upper()} agent")
        task.add_argument("--config", type=Path, default=Path(f"config.{role}.json"))
        task.add_argument("--debug", action="store_true")
    initial = subs.add_parser("init", help="create private JSON config with random tokens")
    initial.add_argument("role", choices=("a", "b"))
    initial.add_argument("--config", type=Path)
    args = cli.parse_args()
    if args.command == "init":
        path = args.config or Path(f"config.{args.role}.json")
        try:
            config = init_config(path, args.role)
        except (FileExistsError, OSError, ValueError) as exc:
            print(exc, file=sys.stderr)
            return 1
        print(f"Created private {path} (do not commit to GitHub)")
        print(f"Web admin_token: {config['admin_token']}")
        print("Copy A control_token and vless_uuid into B via the respective Web UIs.")
        print("Set both xray_bin executable paths and A control_host in Web UI before testing.")
        return 0
    logging.basicConfig(level=logging.DEBUG if args.debug else logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    try:
        asyncio.run(run(args.command, args.config))
    except KeyboardInterrupt:
        return 0
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"mytrn failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
